In [2]:
import numpy as np

In [3]:
np.random.normal(size=10)  

array([-0.13392261, -0.20865933,  0.08544128, -1.50779321,  0.08787665,
       -1.03259971,  0.30369501, -0.04624885, -0.81570893,  1.3005838 ])

In [4]:
def call_payoff(spot_price: float, strike_price: float) -> np.ndarray:
    return np.maximum(spot_price - strike_price, 0.0)

In [5]:
def put_payoff(spot_price: float, strike_price: float) -> np.ndarray:
    return np.maximum(strike_price - spot_price, 0.0)

In [7]:
prices = np.linspace(start=100.0, stop=200.0, num=10)

In [8]:
prices

array([100.        , 111.11111111, 122.22222222, 133.33333333,
       144.44444444, 155.55555556, 166.66666667, 177.77777778,
       188.88888889, 200.        ])

In [9]:
strike = 120.0
call_payoff(prices, strike)

array([ 0.        ,  0.        ,  2.22222222, 13.33333333, 24.44444444,
       35.55555556, 46.66666667, 57.77777778, 68.88888889, 80.        ])